FROM maven:3.9.4-eclipse-temurin-17 AS build

WORKDIR /app

COPY pom.xml .
COPY src ./src

# Pre-download dependencies for faster builds
RUN mvn -B -DskipTests dependency:go-offline

# Default command → run tests
CMD ["mvn", "clean", "test", "-Dbrowser=chrome"]