version: "3.8"
services:
  selenium-chrome:
    image: selenium/standalone-chrome:latest
    container_name: selenium-chrome
    ports:
      - "4444:4444"
    shm_size: 2g

  test-runner:
    build: .
    container_name: selenium-tests
    depends_on:
      - selenium-chrome
    environment:
      - SELENIUM_REMOTE_URL=http://selenium-chrome:4444/wd/hub
      - BROWSER=chrome
    volumes:
    - ./reports:/app/reports
    - ./logs:/app/logs
    - ./post_test.sh:/app/post_test.sh  # script to open the report automatically
    command: ["/bin/bash", "-c", "mvn test && chmod +x /app/post_test.sh && /app/post_test.sh"]
    