version: "3.8"
services:
  selenium-chrome:
    image: selenium/standalone-chrome:latest
    container_name: selenium-chrome
    ports:
      - "4444:4444"
    shm_size: 2g

  test-runner:
    build: .
    depends_on:
      - selenium-chrome
    environment:
      - SELENIUM_REMOTE_URL=http://selenium-chrome:4444/wd/hub
      - BROWSER=chrome
    volumes:
    - ./reports:/app/reports
    - ./target:/app/target
    tty: true